### ISSUE TITLE
csf_pattern district selection bug

### ISSUE THREAD

**Issue by sdrewc** [sfcta/prospector#29]
When a district is selected, and then the user toggles through mode options, previously unselected districts get selected.  

The issue can be replicated by on a fresh load by:
1. select Marina/N. Heights on the chord diagram
2. select Walk/Bike
3. select Transit

Now Marina/N. Heights is still selected, but so is a subset of East Bay

**Comment by crystalxs** [comment]
fix by new pull request

**Comment by sdrewc** [comment]
Looks like this solves the issue
