### ISSUE TITLE
Possible to deselect district by clicking outside of diagram?

### ISSUE THREAD

**Issue by sdrewc** [sfcta/prospector#36]
@crystalxs It would be useful to be able to click anywhere outside of the chord diagram (in the main page, not the sidebar) to deselect a selected district. Can this be done?

**Comment by crystalxs** [comment]
I will try that. Thank you for feedback!

**Comment by crystalxs** [comment]
Fixed by the newest pull request.

**Comment by sdrewc** [comment]
Closed by #38
