### ISSUE TITLE
Intra-district trip "humps"

### ISSUE THREAD

**Issue by sdrewc** [sfcta/prospector#37]
Is it possible to make these shorter? In many cases they're pretty prominent and obscure other chords.  Might be nice to have them a little shorter, but this isn't super important.

**Comment by crystalxs** [comment]
I am not sure if I understand clearly. Do you mean there some trip path overlap with others, misleading users? If yes, I thought we could sort the subgroup paths always from the left hand side district to the right hand side district, then there won't be any overlap. But I tried to coding that, and googling, I found out we cannot modified this part.
Please let me know if I am misunderstanding what you mean.

**Comment by sdrewc** [comment]
@crystalxs What I am referring to are the chords that connect one district with itself, and look like a dome instead of a chord.  What you describe would also be nice to have, but it's useful to know that it can't be done.
